In [41]:
import sqlite3
import pandas as pd

In [42]:
df = pd.read_csv("../data/titanic_cleaned.csv")

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Unknown,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Unknown,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Unknown,Southampton,no,True

In [43]:
conn = sqlite3.connect("../data/titanic.db")

print("Database created successfully!")

Database created successfully!

In [44]:
df.to_sql("titanic", conn, if_exists="replace", index=False)

print("Data imported into SQLite successfully!")

Data imported into SQLite successfully!

In [45]:
query = "SELECT * FROM titanic LIMIT 5;"

result = pd.read_sql(query, conn)

result

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,1,Unknown,Southampton,no,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,0,C,Cherbourg,yes,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,0,Unknown,Southampton,yes,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,Unknown,Southampton,no,1

In [46]:
query = """
SELECT COUNT(*) AS Total_Passengers
FROM titanic;
"""

result = pd.read_sql(query, conn)

result

   Total_Passengers
0               784

In [47]:
query = """
SELECT COUNT(*) AS Survivors
FROM titanic
WHERE survived = 1;
"""

result = pd.read_sql(query, conn)

result

   Survivors
0        323

In [48]:
query = """
SELECT AVG(age) AS Average_Age
FROM titanic;
"""

result = pd.read_sql(query, conn)

result

   Average_Age
0    29.650408

In [49]:
conn.close()
print("Database connection closed successfully!")

Database connection closed successfully!